project_name: ffclient
version: 2



builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    binary: ffclient

archives:
  - 
    formats: ["zip", "binary", "tar.gz"] 

release:
  github:
    owner: FirasSharp
    name: ffclient